config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :rows do
    resources :phones
    collection do
      get :export
      get :import_form
      post :import
    end
  end
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  # number, normalized

  belongs_to :row

  default_scope { order('created_at DESC, id DESC') }

  before_save :normalize

  def normalize
    self.normalized = ::NumberService.normalize(number) if number.present?
  end

  def updated_at_ut
    updated_at.to_time.to_i
  end
end

app/models/row.rb
class Row < ActiveRecord::Base
  # name, avatar, context

  mount_uploader :avatar, AvatarUploader

  default_scope { order('created_at DESC, id DESC') }
  scope :search, lambda {|str| where('name LIKE ?', "%#{str}%")}

  belongs_to :user

  has_many :phones

  before_destroy :destroy_phones

  def random_string
    @randomstring ||= SecureRandom.hex(10)
  end

  def updated_at_ut
    updated_at.to_time.to_i
  end

  private

  def destroy_phones
    Phone.where(:row_id => id).delete_all
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :rows
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    rows_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_filter :authenticate_user!

  before_filter :set_row
  before_filter :set_phone, only: [:edit, :update, :destroy]
  before_filter :check_right_owner

  def index
    @phones = @row.phones
  end

  def new
    @phone = @row.phones.new
  end

  def create
    @phone = @row.phones.new(phones_params)

    if @phone.save
      redirect_to row_phones_path(@row)
    else
      redirect_to new_row_phone_path(@row), :notice => I18n.t('errors.phones.new_save')
    end
  end

  def edit
  end

  def update
    if @phone.update_attributes(phones_params)
      redirect_to row_phones_path(@row)
    else
      redirect_to edit_row_phone_path(@row), :notice => I18n.t('errors.phones.update_save')
    end
  end

  def destroy
    @phone.delete
    redirect_to row_phones_path(@row)
  end

  private

  def set_row
    @row_id = params[:row_id].to_i
    @row = Row.find(@row_id)
  end

  def set_phone
    @phone_id = params[:id].to_i
    @phone = Phone.find(@phone_id)
  end

  def check_right_owner
    if @row.present?
      if @row.user_id != current_user.id
        redirect_to rows_path, :notice => I18n.t('errors.have_not_rights')
      end
    end
  end

  def phones_params
    params.require(:phone).permit(:number)
  end
end

app/controllers/rows_controller.rb
class RowsController < ApplicationController
  before_filter :authenticate_user!

  before_filter :set_row, only: [:edit, :update, :destroy]
  before_filter :set_page, only: [:index, :edit, :update]
  before_filter :set_per_page, only: [:index]
  before_filter :check_right_owner, only: [:edit, :update, :destroy]

  def index
    rows = current_user.rows

    if params[:search].present?
      rows = rows.search(params[:search])
    end

    if @per_page > 0
      @rows = rows.page(@page).per(@per_page)
    else
      @rows = rows.all
    end
  end

  def new
    @row = current_user.rows.new
  end

  def create
    @row = current_user.rows.new(new_row_params)

    if @row.save
      if params[:row][:phones].present?
        params[:row][:phones].split("\n").each do |num|
          num = num.chomp
          phone = @row.phones.new({:number => num})
          phone.save
        end
      end
      redirect_to rows_path
    else
      redirect_to new_row_path, :notice => I18n.t('errors.rows.new_save')
    end
  end

  def edit
  end

  def update
    if @row.update_attributes(new_row_params)
      redirect_to rows_path(:page => params[:row][:page])
    else
      redirect_to edit_row_path(:page => params[:row][:page]), :notice => I18n.t('errors.rows.update_save')
    end
  end

  def destroy
    @row.remove_avatar!
    @row.destroy
    redirect_to rows_path
  end

  def export
    send_data ::ExportService.export(current_user), :type => 'text/csv; charset=UTF-8;', :disposition => "attachment; filename=contacts.csv"
  end

  def import_form
  end

  def import
    file = params[:contacts]
    ::ExportService.import(file.read, current_user)
    redirect_to rows_path, :notice => I18n.t('rows.import_success')
  end

  private

  def set_row
    @row_id = params[:id].to_i
    @row = Row.find(@row_id)
  end

  def set_page
    @page = 1
    @page = params[:page].to_i if params[:page].present?
  end

  def set_per_page
    params_size = if params[:size].present?
      session[:page_size] = params[:size]
    else
      session[:page_size] || 5
    end

    if params_size.present?
      if params_size == 'all'
        @per_page = -1
      else
        @per_page = params_size.to_i
      end
    end
  end

  def check_right_owner
    if @row.present?
      if @row.user_id != current_user.id
        redirect_to rows_path, :notice => I18n.t('errors.have_not_rights')
      end
    end
  end

  def new_row_params
    params.require(:row).permit(:name, :context, :avatar)
  end
end

app/views/home/index.html.haml
%h1
  Тестовое задание
%p
  Реализация телефонной книги.

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to I18n.t('menu.home'), (current_user.present? ? rows_path : root_path), class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/navigation_links_right'

app/views/layouts/_navigation_links_right.html.haml
- if user_signed_in?
  %li
    = link_to I18n.t('menu.logout'), destroy_user_session_path, :method => :delete
- else
  %li
    = link_to I18n.t('menu.login'), new_user_session_path
  %li
    = link_to I18n.t('menu.signup'), new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Test Browsec'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Test Browsec'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/phones/edit.html.haml
%h2{:align => 'center'}
  = I18n.t('phones.edit_title')
.form-container
  = form_for [@row, @phone], :html => {:role => 'form', :class => 'forms' } do |f|
    .form-group
      %label{ for: "number" }
        = I18n.t('phones.number_label')
      = f.text_field :number, class: 'form-control'
    %button.btn.btn-success{ type: 'submit' }
      = I18n.t('phones.save')

app/views/phones/index.html.haml
%h2
  = I18n.t('phones_title') % {:name => @row.name}

.btn-group.left
  = link_to new_row_phone_path(@row) do
    %button.btn.btn-primary.btn-actions
      = I18n.t('new')
%br
%br
%table.table.table-bordered.table-condensed.table-striped.phones-table
  %tr
    %th.avatar
      = I18n.t('phones.number')
  - if @phones.present?
    - @phones.each do |phone|
      %tr
        %td.middle
          .btn-group.left
            %b
              = phone.number
          .btn-group.right
            = link_to edit_row_phone_path(@row, phone.id), class: 'action_glyph' do
              %span.glyphicon.glyphicon-edit
            = link_to row_phone_path(@row, phone.id), :method => :delete, :data => {:confirm => I18n.t("delete_sure")}, class: 'action_glyph' do
              %span.glyphicon.glyphicon-remove

app/views/phones/new.html.haml
%h2{:align => 'center'}
  = I18n.t('phones.new_title')
.form-container
  = form_for [@row, @phone], :html => {:role => 'form', :class => 'forms' } do |f|
    .form-group
      %label{ for: "number" }
        = I18n.t('phones.number_label')
      = f.text_field :number, class: 'form-control'
    %button.btn.btn-success{ type: 'submit' }
      = I18n.t('phones.save')

app/views/rows/edit.html.haml
%h2{:align => 'center'}
  = I18n.t('rows.new_title')
.form-container
  = form_for [@row], :html => { :multipart => true, :role => 'form', :class => 'forms' } do |f|
    = f.hidden_field :page, :value => @page
    = f.hidden_field :size, :value => params[:size]
    .form-group
      %label{ for: "name" }
        = I18n.t('rows.name_label')
      = f.text_field :name, class: 'form-control'
    .form-group
      %label{ for: "context" }
        = I18n.t('rows.context_label')
      = f.text_field :context, class: 'form-control'
    .form-group
      %label{ for: "avatar" }
        = I18n.t('rows.avatar_label')
      = f.file_field :avatar, :style => 'width: 30%;', class: 'form-control'
    %button.btn.btn-success{ type: 'submit' }
      = I18n.t('rows.save')

app/views/rows/import_form.html.haml
%h2
  = I18n.t('rows.import_title')
.form-container
  %form.forms{:action => import_rows_path, :enctype => 'multipart/form-data', :role => 'form', :method => 'POST' }
    %input{ :type => 'hidden', :name => request_forgery_protection_token.to_s, :value => form_authenticity_token }
    .form-group
      %label{ for: 'phonesfile' }
        = I18n.t('rows.phonesfile_label')
      %input.form-control{:type => 'file', :name => 'contacts', :style => 'width: 30%;'}
    %button.btn.btn-success{ type: 'submit' }
      = I18n.t('rows.save')

app/views/rows/index.html.haml
%h2
  = I18n.t('phone_book')

.btn-group.left
  = link_to new_row_path do
    %button.btn.btn-primary.btn-actions
      = I18n.t('new')

.btn-group.right
  - if @per_page == 5
    - active_5 = 'active'
  - if @per_page == 10
    - active_10 = 'active'
  - if @per_page == 25
    - active_25 = 'active'
  - if @per_page < 0
    - active_all = 'active'
  = link_to rows_path(:page => @page, :size => 5), :class => "btn btn-default #{active_5}" do
    5
  = link_to rows_path(:page => @page, :size => 10), :class => "btn btn-default #{active_10}" do
    10
  = link_to rows_path(:page => @page, :size => 25), :class => "btn btn-default #{active_25}" do
    25
  = link_to rows_path(:page => @page, :size => 'all'), :class => "btn btn-default #{active_all}" do
    = I18n.t('rows.all')

.form-container-search
  = form_for rows_path, :html => {:role => 'search', :class => 'search-form form-horizontal', :method => 'GET', :id => 'search_form' } do |f|
    .input-group.add-on
      %input{:type => 'hidden', :name => 'size', :value => params[:size] }
      %input{:type => 'text', :name => 'search', id: 'search_field', class: 'form-control', placeholder: I18n.t('search'), :value => params[:search] }
      .input-group-btn
        %button.btn.btn-default.search_reset{ type: "button" }
          %i.glyphicon.glyphicon-remove
        %button.btn.btn-default{ type: "submit" }
          %i.glyphicon.glyphicon-search
%br
%table.table.table-bordered.table-condensed.table-striped
  %tr
    %th.avatar
      = I18n.t('rows.avatar')
    %th
      = I18n.t('rows.name')
    %th.half
      = I18n.t('rows.phones')
  - if @rows.present?
    - @rows.each do |row|
      %tr
        %td
          - if row.avatar.present?
            %img{:alt => row.name, :src => row.avatar.url}
        %td.middle
          .btn-group
            %b
              = row.name
            - if row.context.present?
              %br
              %small
                %i
                  = "(#{row.context})"
          %br
          .btn-group
            = link_to edit_row_path(row.id, :page => @page, :size => params[:size]), class: 'action_glyph' do
              %span.glyphicon.glyphicon-edit
            = link_to row_path(row.id, :size => params[:size]), :method => :delete, :data => {:confirm => I18n.t("delete_sure")}, class: 'action_glyph' do
              %span.glyphicon.glyphicon-remove
        %td.middle
          .btn-group
            = row.phones.pluck(:number).join(', ')
          %br
          .btn-group
            = link_to row_phones_path(row.id), class: 'action_glyph' do
              %span.glyphicon.glyphicon-list
.btn-group.left
  = link_to export_rows_path, class: 'action_glyph' do
    %button.btn.btn-primary.btn-actions
      = I18n.t('rows.export')
  = link_to import_form_rows_path, class: 'action_glyph' do
    %button.btn.btn-primary.btn-actions
      = I18n.t('rows.import')

- if @per_page > 0
  = paginate @rows, :theme => 'twitter-bootstrap-3'

app/views/rows/new.html.haml
%h2{:align => 'center'}
  = I18n.t('rows.new_title')
.form-container
  = form_for [@row], :html => { :multipart => true, :role => 'form', :class => 'forms' } do |f|
    .form-group
      %label{ for: "name" }
        = I18n.t('rows.name_label')
      = f.text_field :name, class: 'form-control'
    .form-group
      %label{ for: "context" }
        = I18n.t('rows.context_label')
      = f.text_field :context, class: 'form-control'
    .form-group
      %label{ for: "avatar" }
        = I18n.t('rows.avatar_label')
      = f.file_field :avatar, :style => 'width: 30%;', class: 'form-control'
    .form-group
      %label{ for: "phones" }
        = I18n.t('rows.phones_label')
      = f.text_area :phones, class: 'form-control', :value => '', :rows => 5
    %button.btn.btn-success{ type: 'submit' }
      = I18n.t('rows.save')